#version: '3'

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80" #http
      - "443:443" #https
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
    depends_on:
      - web
    networks:
      - app_network

  web:
    build: .
    restart: unless-stopped
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - DJANGO_SETTINGS_MODULE=Test_StayFlow.settings
#      - EMAIL_HOST=maildev
#      - EMAIL_PORT=1025
#      - EMAIL_USE_TLS=0

    depends_on:
      dbMySQL:
        condition: service_healthy
  #    maildev:
  #      condition: service_started
    networks:
      - app_network

  dbMySQL:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:

      - ./mysql_db:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT}"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app_network

 #maildev:
 #  image: maildev/maildev
 #  restart: always
 #  environment:
 #    - TZ=Europe/Berlin
 #    - MAILDEV_WEB_PORT=1080
 #    - MAILDEV_SMTP_PORT=1025
 #  ports:
 #    - "9090:1080"
 #    - "1025:1025"
 #  logging:
 #    driver: "json-file"
 #    options:
 #      max-size: "1m"
 #  networks:
 #    - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
