# Generated by Django 5.2.1 on 2025-05-20 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms', models.PositiveIntegerField()),
                ('property_type', models.CharField(choices=[('SINGLE_ROOM', 'Single room (studio)'), ('ONE_BEDROOM', 'One room with a separate bedroom'), ('TWO_BEDROOM', 'Two rooms with shared bathroom'), ('TWO_BEDROOM_ENSUITE', 'Two rooms with private bathrooms'), ('THREE_BEDROOM', 'Three rooms'), ('SUITE', 'Suite / Apartment'), ('SHARED_ROOM', 'Shared room / bedspace'), ('PRIVATE_ROOM_IN_SHARED', 'Private room in a shared apartment'), ('LOFT', 'Loft / Attic'), ('STUDIO', 'Studio')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_daily_available', models.BooleanField(default=False)),
                ('daily_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_monthly_available', models.BooleanField(default=False)),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
