# Generated by Django 5.2.1 on 2025-05-20 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='price',
        ),
    ]
