# Generated by Django 5.2.1 on 2025-05-21 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('rent', '0002_remove_rent_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='daily_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per day (if daily rental is enabled).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='description',
            field=models.TextField(help_text='Full description of the property: layout, amenities, rental conditions, etc.'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to temporarily hide this listing from users.'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='is_daily_available',
            field=models.BooleanField(default=False, help_text='Is daily rental available for this property?'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='is_monthly_available',
            field=models.BooleanField(default=False, help_text='Price per month (if monthly rental is enabled).'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='location',
            field=models.ForeignKey(help_text='Select the location (city/area) where the property is situated.', on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='location.location'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='owner',
            field=models.ForeignKey(help_text='Select the user who is posting the listing (typically a host).', on_delete=django.db.models.deletion.CASCADE, related_name='rents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rent',
            name='property_type',
            field=models.CharField(choices=[('SINGLE_ROOM', 'Single room (studio)'), ('ONE_BEDROOM', 'One room with a separate bedroom'), ('TWO_BEDROOM', 'Two rooms with shared bathroom'), ('TWO_BEDROOM_ENSUITE', 'Two rooms with private bathrooms'), ('THREE_BEDROOM', 'Three rooms'), ('SUITE', 'Suite / Apartment'), ('SHARED_ROOM', 'Shared room / bedspace'), ('PRIVATE_ROOM_IN_SHARED', 'Private room in a shared apartment'), ('LOFT', 'Loft / Attic'), ('STUDIO', 'Studio')], help_text='Select the type of property: studio, apartment, house, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='rent',
            name='rooms',
            field=models.PositiveIntegerField(help_text='Enter the number of rooms in the property.'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='title',
            field=models.CharField(help_text="Short title of the listing, e.g., 'Cozy studio in central Berlin'.", max_length=255),
        ),
    ]
