# Generated by Django 5.2.1 on 2025-05-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_add_location_field'),
    ]

    operations = [
    ]
