# Generated by Django 5.2.1 on 2025-05-26 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('rent', '0005_sync_after_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='location',
            field=models.ForeignKey(default=0, help_text='Select the location (city/area) where the property is situated.', on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='location.location'),
            preserve_default=False,
        ),
    ]
