# Generated by Django 5.2.1 on 2025-05-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_rent_view_count_alter_rent_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
