# Generated by Django 5.2.1 on 2025-05-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_rent_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Daily rental price in EUR', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rent',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=10),
            preserve_default=False,
        ),
    ]
