# Generated by Django 5.2.1 on 2025-05-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0008_alter_rent_daily_price_alter_rent_monthly_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='daily_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily rental price in EUR', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
