# Generated by Django 5.2.1 on 2025-05-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0009_alter_rent_daily_price_alter_rent_monthly_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rent',
            name='ratings_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
