# Generated by Django 5.2.1 on 2025-06-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0010_rent_average_rating_rent_ratings_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
