# Generated by Django 5.2.1 on 2025-05-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated platform commission in EUR', max_digits=10),
        ),
    ]
