# Generated by Django 5.2.1 on 2025-05-28 19:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bookinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price without commission', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.15'), help_text='0.15 = 15%', max_digits=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='base + commission', max_digits=10),
        ),
    ]
